use serde::Deserialize;
use std::collections::BTreeMap;
use std::process::Command;

const SEED: &str = "#6750A4";

#[derive(Deserialize)]
struct MatugenOutput {
    colors: Modes,
}

#[derive(Deserialize)]
struct Modes {
    light: BTreeMap<String, String>,
    dark: BTreeMap<String, String>,
}

// (matugen role key, QML property name). QML reserves the `onXxx` naming
// pattern for signal handlers, so a property cannot be literally named
// e.g. `onSurface` — roles matugen calls `on_*` are suffixed `*Text`
// instead (matching the convention already used in this machine's
// quickshell config's ColorProvider.qml, which hit the same issue).
const ROLES: &[(&str, &str)] = &[
    ("primary", "primary"),
    ("on_primary", "primaryText"),
    ("primary_container", "primaryContainer"),
    ("on_primary_container", "primaryContainerText"),
    ("secondary", "secondary"),
    ("on_secondary", "secondaryText"),
    ("secondary_container", "secondaryContainer"),
    ("on_secondary_container", "secondaryContainerText"),
    ("tertiary", "tertiary"),
    ("on_tertiary", "tertiaryText"),
    ("tertiary_container", "tertiaryContainer"),
    ("on_tertiary_container", "tertiaryContainerText"),
    ("error", "error"),
    ("on_error", "errorText"),
    ("error_container", "errorContainer"),
    ("on_error_container", "errorContainerText"),
    ("surface", "surface"),
    ("on_surface", "surfaceText"),
    ("on_surface_variant", "surfaceVariantText"),
    ("surface_container_lowest", "surfaceContainerLowest"),
    ("surface_container_low", "surfaceContainerLow"),
    ("surface_container", "surfaceContainer"),
    ("surface_container_high", "surfaceContainerHigh"),
    ("surface_container_highest", "surfaceContainerHighest"),
    ("outline", "outline"),
    ("outline_variant", "outlineVariant"),
    ("inverse_surface", "inverseSurface"),
    ("inverse_on_surface", "inverseOnSurface"),
    ("inverse_primary", "inversePrimary"),
];

fn render_group(colors: &BTreeMap<String, String>) -> String {
    let mut out = String::new();
    for (matugen_key, qml_name) in ROLES {
        let hex = colors
            .get(*matugen_key)
            .unwrap_or_else(|| panic!("matugen output missing role: {matugen_key}"));
        out.push_str(&format!("        readonly property color {qml_name}: \"{hex}\"\n"));
    }
    out
}

fn main() {
    let output = Command::new("matugen")
        .args([
            "color",
            "hex",
            SEED,
            "--type",
            "scheme-tonal-spot",
            "--json",
            "hex",
            "--dry-run",
            "--quiet",
        ])
        .output()
        .expect("failed to run matugen — is it installed and on PATH?");

    if !output.status.success() {
        panic!(
            "matugen exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let parsed: MatugenOutput =
        serde_json::from_slice(&output.stdout).expect("failed to parse matugen JSON output");

    let qml = format!(
        "pragma Singleton\nimport QtQuick\n\nQtObject {{\n    id: root\n\n    // Generated by `cargo run -p fm-xtask` from seed {seed} via matugen\n    // (scheme-tonal-spot). Do not hand-edit — regenerate instead.\n\n    property bool darkMode: false\n\n    readonly property QtObject light: QtObject {{\n{light}    }}\n\n    readonly property QtObject dark: QtObject {{\n{dark}    }}\n\n    readonly property QtObject scheme: darkMode ? dark : light\n}}\n",
        seed = SEED,
        light = render_group(&parsed.colors.light),
        dark = render_group(&parsed.colors.dark),
    );

    let out_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../app/qml/tokens/Color.qml");
    std::fs::create_dir_all(out_path.parent().unwrap()).expect("failed to create tokens dir");
    std::fs::write(&out_path, qml).expect("failed to write Color.qml");
    println!("wrote {}", out_path.display());
}
