use serde::Deserialize;
use std::collections::BTreeMap;
use std::process::Command;

const SEED: &str = "#6750A4";

#[derive(Deserialize)]
struct MatugenOutput {
    colors: Modes,
}

#[derive(Deserialize)]
struct Modes {
    light: BTreeMap<String, String>,
    dark: BTreeMap<String, String>,
}

// (matugen role key, QML property name). QML reserves the `onXxx` naming
// pattern for signal handlers, so a property cannot be literally named
// e.g. `onSurface` — roles matugen calls `on_*` are suffixed `*Text`
// instead (matching the convention already used in this machine's
// quickshell config's ColorProvider.qml, which hit the same issue).
const ROLES: &[(&str, &str)] = &[
    ("primary", "primary"),
    ("on_primary", "primaryText"),
    ("primary_container", "primaryContainer"),
    ("on_primary_container", "primaryContainerText"),
    ("secondary", "secondary"),
    ("on_secondary", "secondaryText"),
    ("secondary_container", "secondaryContainer"),
    ("on_secondary_container", "secondaryContainerText"),
    ("tertiary", "tertiary"),
    ("on_tertiary", "tertiaryText"),
    ("tertiary_container", "tertiaryContainer"),
    ("on_tertiary_container", "tertiaryContainerText"),
    ("error", "error"),
    ("on_error", "errorText"),
    ("error_container", "errorContainer"),
    ("on_error_container", "errorContainerText"),
    ("surface", "surface"),
    ("on_surface", "surfaceText"),
    ("on_surface_variant", "surfaceVariantText"),
    ("surface_container_lowest", "surfaceContainerLowest"),
    ("surface_container_low", "surfaceContainerLow"),
    ("surface_container", "surfaceContainer"),
    ("surface_container_high", "surfaceContainerHigh"),
    ("surface_container_highest", "surfaceContainerHighest"),
    ("outline", "outline"),
    ("outline_variant", "outlineVariant"),
    ("inverse_surface", "inverseSurface"),
    ("inverse_on_surface", "inverseOnSurface"),
    ("inverse_primary", "inversePrimary"),
];

fn render_group(colors: &BTreeMap<String, String>) -> String {
    let mut out = String::new();
    for (matugen_key, qml_name) in ROLES {
        let hex = colors
            .get(*matugen_key)
            .unwrap_or_else(|| panic!("matugen output missing role: {matugen_key}"));
        out.push_str(&format!("        readonly property color {qml_name}: \"{hex}\"\n"));
    }
    out
}

/// The external color file's key names match this app's own QML property
/// names for every role except this one — the user's quickshell color
/// generator (gen_colors.py) calls it `inverseSurfaceText` where this
/// app's convention (on_* -> *Text) would produce `inverseOnSurface`.
fn external_key_for(qml_name: &str) -> &str {
    match qml_name {
        "inverseOnSurface" => "inverseSurfaceText",
        other => other,
    }
}

/// Each role falls back to the generated dark palette's value when the
/// external color file doesn't define it.
fn render_custom_group() -> String {
    let mut out = String::new();
    for (_, qml_name) in ROLES {
        let external_key = external_key_for(qml_name);
        out.push_str(&format!(
            "        readonly property color {qml_name}: root._customColor(\"{external_key}\", root.dark.{qml_name})\n"
        ));
    }
    out
}

fn main() {
    let output = Command::new("matugen")
        .args([
            "color",
            "hex",
            SEED,
            "--type",
            "scheme-tonal-spot",
            "--json",
            "hex",
            "--dry-run",
            "--quiet",
        ])
        .output()
        .expect("failed to run matugen — is it installed and on PATH?");

    if !output.status.success() {
        panic!(
            "matugen exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let parsed: MatugenOutput =
        serde_json::from_slice(&output.stdout).expect("failed to parse matugen JSON output");

    let qml = format!(
        "pragma Singleton\nimport QtQuick\n\nQtObject {{\n    id: root\n\n    // Generated by `cargo run -p fm-xtask` from seed {seed} via matugen\n    // (scheme-tonal-spot). Do not hand-edit — regenerate instead.\n\n    property bool darkMode: false\n\n    // Populated by loadCustomColors() from an external JSON color file\n    // (e.g. a wallpaper-based Material You generator, matched by role\n    // name against this app's own token names) if one exists at the\n    // given path; stays null otherwise, in which case `scheme` falls\n    // back to the generated light/dark palettes below.\n    property var custom: null\n\n    function _customColor(key, fallback) {{\n        return (root.custom && root.custom[key]) ? root.custom[key] : fallback\n    }}\n\n    // Reads and applies an external color file written by another tool.\n    // Safe to call with a path that doesn't exist (or isn't valid JSON) —\n    // silently leaves `custom` unset so `scheme` keeps using the\n    // generated palette. Call once, after the path is known (e.g. from\n    // FileListModel.themeColorsPath), not from Component.onCompleted here\n    // — this is a singleton that may be instantiated before that path is\n    // resolvable.\n    function loadCustomColors(path) {{\n        if (!path || path.length === 0) {{\n            return\n        }}\n        var xhr = new XMLHttpRequest()\n        xhr.open(\"GET\", \"file://\" + path, false)\n        xhr.send()\n        if (xhr.status !== 200 && xhr.status !== 0) {{\n            return\n        }}\n        if (!xhr.responseText || xhr.responseText.length === 0) {{\n            return\n        }}\n        try {{\n            root.custom = JSON.parse(xhr.responseText)\n        }} catch (e) {{\n            console.warn(\"Color.qml: failed to parse custom color file:\", e)\n        }}\n    }}\n\n    readonly property QtObject light: QtObject {{\n{light}    }}\n\n    readonly property QtObject dark: QtObject {{\n{dark}    }}\n\n    readonly property QtObject customScheme: QtObject {{\n{custom}    }}\n\n    readonly property QtObject scheme: custom !== null ? customScheme : (darkMode ? dark : light)\n}}\n",
        seed = SEED,
        light = render_group(&parsed.colors.light),
        dark = render_group(&parsed.colors.dark),
        custom = render_custom_group(),
    );

    let out_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../app/qml/tokens/Color.qml");
    std::fs::create_dir_all(out_path.parent().unwrap()).expect("failed to create tokens dir");
    std::fs::write(&out_path, qml).expect("failed to write Color.qml");
    println!("wrote {}", out_path.display());
}
