use serde::Deserialize;
use std::collections::BTreeMap;
use std::process::Command;

const SEED: &str = "#6750A4";

#[derive(Deserialize)]
struct MatugenOutput {
    colors: Modes,
}

#[derive(Deserialize)]
struct Modes {
    light: BTreeMap<String, String>,
    dark: BTreeMap<String, String>,
}

const ROLES: &[&str] = &[
    "primary",
    "on_primary",
    "primary_container",
    "on_primary_container",
    "secondary",
    "on_secondary",
    "secondary_container",
    "on_secondary_container",
    "tertiary",
    "on_tertiary",
    "tertiary_container",
    "on_tertiary_container",
    "error",
    "on_error",
    "error_container",
    "on_error_container",
    "surface",
    "on_surface",
    "on_surface_variant",
    "surface_container_lowest",
    "surface_container_low",
    "surface_container",
    "surface_container_high",
    "surface_container_highest",
    "outline",
    "outline_variant",
    "inverse_surface",
    "inverse_on_surface",
    "inverse_primary",
];

fn to_camel(role: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for ch in role.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(ch.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn render_group(colors: &BTreeMap<String, String>) -> String {
    let mut out = String::new();
    for role in ROLES {
        let hex = colors
            .get(*role)
            .unwrap_or_else(|| panic!("matugen output missing role: {role}"));
        out.push_str(&format!("        readonly property color {}: \"{}\"\n", to_camel(role), hex));
    }
    out
}

fn main() {
    let output = Command::new("matugen")
        .args([
            "color",
            "hex",
            SEED,
            "--type",
            "scheme-tonal-spot",
            "--json",
            "hex",
            "--dry-run",
            "--quiet",
        ])
        .output()
        .expect("failed to run matugen — is it installed and on PATH?");

    if !output.status.success() {
        panic!(
            "matugen exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let parsed: MatugenOutput =
        serde_json::from_slice(&output.stdout).expect("failed to parse matugen JSON output");

    let qml = format!(
        "pragma Singleton\nimport QtQuick\n\nQtObject {{\n    id: root\n\n    // Generated by `cargo run -p fm-xtask` from seed {seed} via matugen\n    // (scheme-tonal-spot). Do not hand-edit — regenerate instead.\n\n    property bool darkMode: false\n\n    readonly property QtObject light: QtObject {{\n{light}    }}\n\n    readonly property QtObject dark: QtObject {{\n{dark}    }}\n\n    readonly property QtObject scheme: darkMode ? dark : light\n}}\n",
        seed = SEED,
        light = render_group(&parsed.colors.light),
        dark = render_group(&parsed.colors.dark),
    );

    let out_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../app/qml/tokens/Color.qml");
    std::fs::create_dir_all(out_path.parent().unwrap()).expect("failed to create tokens dir");
    std::fs::write(&out_path, qml).expect("failed to write Color.qml");
    println!("wrote {}", out_path.display());
}
