use cxx_qt_build::{CxxQtBuilder, QmlFile, QmlModule};

fn main() {
    CxxQtBuilder::new_qml_module(
        QmlModule::new("com.filemanager.app")
            .qml_files([
                "qml/main.qml",
                "qml/util/format.js",
                "qml/shapes/material-shapes.js",
                "qml/shapes/MorphShape.qml",
                "qml/shapes/geometry/offset.js",
                "qml/shapes/graphics/matrix.js",
                "qml/shapes/shapes/corner-rounding.js",
                "qml/shapes/shapes/cubic.js",
                "qml/shapes/shapes/feature.js",
                "qml/shapes/shapes/feature-mapping.js",
                "qml/shapes/shapes/float-mapping.js",
                "qml/shapes/shapes/morph.js",
                "qml/shapes/shapes/point.js",
                "qml/shapes/shapes/polygon-measure.js",
                "qml/shapes/shapes/rounded-corner.js",
                "qml/shapes/shapes/rounded-polygon.js",
                "qml/shapes/shapes/utils.js",
                "qml/shapes/ShapeCanvas.qml",
                "qml/components/Ripple.qml",
                "qml/components/Icon.qml",
                "qml/components/Tooltip.qml",
                "qml/components/Button.qml",
                "qml/components/ButtonGroup.qml",
                "qml/components/ShapeLoader.qml",
                "qml/components/WavyProgressBar.qml",
                "qml/components/FileListItem.qml",
                "qml/components/FileGridItem.qml",
                "qml/components/TopAppBar.qml",
                "qml/components/PathBar.qml",
                "qml/components/ViewOptionsMenu.qml",
                "qml/components/GroupCard.qml",
                "qml/components/ScrollBar.qml",
                "qml/components/Sidebar.qml",
                "qml/components/ContextMenu.qml",
                "qml/components/ItemContextMenu.qml",
                "qml/components/TrashContextMenu.qml",
                "qml/components/NewFolderDialog.qml",
                "qml/components/RenameDialog.qml",
                "qml/components/PropertiesDialog.qml",
                "qml/components/ConfirmDialog.qml",
                "qml/components/SettingsDialog.qml",
                "qml/components/LinearWavyProgressBar.qml",
                "qml/components/TransferStatus.qml",
            ])
            .qml_file(QmlFile::from("qml/tokens/Color.qml").singleton(true))
            .qml_file(QmlFile::from("qml/tokens/Type.qml").singleton(true))
            .qml_file(QmlFile::from("qml/tokens/Shape.qml").singleton(true))
            .qml_file(QmlFile::from("qml/tokens/Elevation.qml").singleton(true))
            .qml_file(QmlFile::from("qml/tokens/Motion.qml").singleton(true)),
    )
    .file("src/file_list_model.rs")
    .qt_module("Gui")
    .qt_module("QuickLayouts")
    .build();
}
