pragma Singleton
import QtQuick

QtObject {
    id: root

    // Generated by `cargo run -p fm-xtask` from seed #6750A4 via matugen
    // (scheme-tonal-spot). Do not hand-edit — regenerate instead.

    property bool darkMode: false

    // Populated by applyCustomColors() from an external JSON color file's
    // contents (e.g. a wallpaper-based Material You generator, matched by
    // role name against this app's own token names) if one was found;
    // stays null otherwise, in which case `scheme` falls back to the
    // generated light/dark palettes below.
    property var custom: null

    function _customColor(key, fallback) {
        return (root.custom && root.custom[key]) ? root.custom[key] : fallback
    }

    // Parses and applies an external color file's raw JSON text. Reading
    // the file itself happens on the Rust side (FileListModel.
    // readThemeColorsFile()) rather than here via QML's XMLHttpRequest —
    // Qt disables local file reads through XHR by default
    // (QML_XHR_ALLOW_FILE_READ), and requiring users to set an env var
    // just to use a color file isn't reasonable. Safe to call with an
    // empty string (missing file) or invalid JSON — silently leaves
    // `custom` unset so `scheme` keeps using the generated palette. Call
    // once, after FileListModel exists — this is a singleton that may be
    // instantiated before that, so it can't read the file itself from
    // Component.onCompleted here.
    function applyCustomColors(text) {
        if (!text || text.length === 0) {
            return
        }
        try {
            root.custom = JSON.parse(text)
        } catch (e) {
            console.warn("Color.qml: failed to parse custom color file:", e)
        }
    }

    readonly property QtObject light: QtObject {
        readonly property color primary: "#65558f"
        readonly property color primaryText: "#ffffff"
        readonly property color primaryContainer: "#e9ddff"
        readonly property color primaryContainerText: "#201047"
        readonly property color secondary: "#625b71"
        readonly property color secondaryText: "#ffffff"
        readonly property color secondaryContainer: "#e8def8"
        readonly property color secondaryContainerText: "#1e192b"
        readonly property color tertiary: "#7e5260"
        readonly property color tertiaryText: "#ffffff"
        readonly property color tertiaryContainer: "#ffd9e3"
        readonly property color tertiaryContainerText: "#31101d"
        readonly property color error: "#ba1a1a"
        readonly property color errorText: "#ffffff"
        readonly property color errorContainer: "#ffdad6"
        readonly property color errorContainerText: "#410002"
        readonly property color surface: "#fdf7ff"
        readonly property color surfaceText: "#1d1b20"
        readonly property color surfaceVariantText: "#49454e"
        readonly property color surfaceContainerLowest: "#ffffff"
        readonly property color surfaceContainerLow: "#f8f2fa"
        readonly property color surfaceContainer: "#f2ecf4"
        readonly property color surfaceContainerHigh: "#ece6ee"
        readonly property color surfaceContainerHighest: "#e6e0e9"
        readonly property color outline: "#7a757f"
        readonly property color outlineVariant: "#cac4cf"
        readonly property color inverseSurface: "#322f35"
        readonly property color inverseOnSurface: "#f5eff7"
        readonly property color inversePrimary: "#cfbdfe"
    }

    readonly property QtObject dark: QtObject {
        readonly property color primary: "#cfbdfe"
        readonly property color primaryText: "#36275d"
        readonly property color primaryContainer: "#4d3d75"
        readonly property color primaryContainerText: "#e9ddff"
        readonly property color secondary: "#cbc2db"
        readonly property color secondaryText: "#332d41"
        readonly property color secondaryContainer: "#4a4458"
        readonly property color secondaryContainerText: "#e8def8"
        readonly property color tertiary: "#efb8c8"
        readonly property color tertiaryText: "#4a2532"
        readonly property color tertiaryContainer: "#633b48"
        readonly property color tertiaryContainerText: "#ffd9e3"
        readonly property color error: "#ffb4ab"
        readonly property color errorText: "#690005"
        readonly property color errorContainer: "#93000a"
        readonly property color errorContainerText: "#ffdad6"
        readonly property color surface: "#141218"
        readonly property color surfaceText: "#e6e0e9"
        readonly property color surfaceVariantText: "#cac4cf"
        readonly property color surfaceContainerLowest: "#0f0d13"
        readonly property color surfaceContainerLow: "#1d1b20"
        readonly property color surfaceContainer: "#211f24"
        readonly property color surfaceContainerHigh: "#2b292f"
        readonly property color surfaceContainerHighest: "#36343a"
        readonly property color outline: "#948f99"
        readonly property color outlineVariant: "#49454e"
        readonly property color inverseSurface: "#e6e0e9"
        readonly property color inverseOnSurface: "#322f35"
        readonly property color inversePrimary: "#65558f"
    }

    readonly property QtObject customScheme: QtObject {
        readonly property color primary: root._customColor("primary", root.dark.primary)
        readonly property color primaryText: root._customColor("primaryText", root.dark.primaryText)
        readonly property color primaryContainer: root._customColor("primaryContainer", root.dark.primaryContainer)
        readonly property color primaryContainerText: root._customColor("primaryContainerText", root.dark.primaryContainerText)
        readonly property color secondary: root._customColor("secondary", root.dark.secondary)
        readonly property color secondaryText: root._customColor("secondaryText", root.dark.secondaryText)
        readonly property color secondaryContainer: root._customColor("secondaryContainer", root.dark.secondaryContainer)
        readonly property color secondaryContainerText: root._customColor("secondaryContainerText", root.dark.secondaryContainerText)
        readonly property color tertiary: root._customColor("tertiary", root.dark.tertiary)
        readonly property color tertiaryText: root._customColor("tertiaryText", root.dark.tertiaryText)
        readonly property color tertiaryContainer: root._customColor("tertiaryContainer", root.dark.tertiaryContainer)
        readonly property color tertiaryContainerText: root._customColor("tertiaryContainerText", root.dark.tertiaryContainerText)
        readonly property color error: root._customColor("error", root.dark.error)
        readonly property color errorText: root._customColor("errorText", root.dark.errorText)
        readonly property color errorContainer: root._customColor("errorContainer", root.dark.errorContainer)
        readonly property color errorContainerText: root._customColor("errorContainerText", root.dark.errorContainerText)
        readonly property color surface: root._customColor("surface", root.dark.surface)
        readonly property color surfaceText: root._customColor("surfaceText", root.dark.surfaceText)
        readonly property color surfaceVariantText: root._customColor("surfaceVariantText", root.dark.surfaceVariantText)
        readonly property color surfaceContainerLowest: root._customColor("surfaceContainerLowest", root.dark.surfaceContainerLowest)
        readonly property color surfaceContainerLow: root._customColor("surfaceContainerLow", root.dark.surfaceContainerLow)
        readonly property color surfaceContainer: root._customColor("surfaceContainer", root.dark.surfaceContainer)
        readonly property color surfaceContainerHigh: root._customColor("surfaceContainerHigh", root.dark.surfaceContainerHigh)
        readonly property color surfaceContainerHighest: root._customColor("surfaceContainerHighest", root.dark.surfaceContainerHighest)
        readonly property color outline: root._customColor("outline", root.dark.outline)
        readonly property color outlineVariant: root._customColor("outlineVariant", root.dark.outlineVariant)
        readonly property color inverseSurface: root._customColor("inverseSurface", root.dark.inverseSurface)
        readonly property color inverseOnSurface: root._customColor("inverseSurfaceText", root.dark.inverseOnSurface)
        readonly property color inversePrimary: root._customColor("inversePrimary", root.dark.inversePrimary)
    }

    readonly property QtObject scheme: custom !== null ? customScheme : (darkMode ? dark : light)
}
