pragma Singleton
import QtQuick

QtObject {
    id: root

    // Generated by `cargo run -p fm-xtask` from seed #6750A4 via matugen
    // (scheme-tonal-spot). Do not hand-edit — regenerate instead.

    property bool darkMode: false

    readonly property QtObject light: QtObject {
        readonly property color primary: "#65558f"
        readonly property color primaryText: "#ffffff"
        readonly property color primaryContainer: "#e9ddff"
        readonly property color primaryContainerText: "#201047"
        readonly property color secondary: "#625b71"
        readonly property color secondaryText: "#ffffff"
        readonly property color secondaryContainer: "#e8def8"
        readonly property color secondaryContainerText: "#1e192b"
        readonly property color tertiary: "#7e5260"
        readonly property color tertiaryText: "#ffffff"
        readonly property color tertiaryContainer: "#ffd9e3"
        readonly property color tertiaryContainerText: "#31101d"
        readonly property color error: "#ba1a1a"
        readonly property color errorText: "#ffffff"
        readonly property color errorContainer: "#ffdad6"
        readonly property color errorContainerText: "#410002"
        readonly property color surface: "#fdf7ff"
        readonly property color surfaceText: "#1d1b20"
        readonly property color surfaceVariantText: "#49454e"
        readonly property color surfaceContainerLowest: "#ffffff"
        readonly property color surfaceContainerLow: "#f8f2fa"
        readonly property color surfaceContainer: "#f2ecf4"
        readonly property color surfaceContainerHigh: "#ece6ee"
        readonly property color surfaceContainerHighest: "#e6e0e9"
        readonly property color outline: "#7a757f"
        readonly property color outlineVariant: "#cac4cf"
        readonly property color inverseSurface: "#322f35"
        readonly property color inverseOnSurface: "#f5eff7"
        readonly property color inversePrimary: "#cfbdfe"
    }

    readonly property QtObject dark: QtObject {
        readonly property color primary: "#cfbdfe"
        readonly property color primaryText: "#36275d"
        readonly property color primaryContainer: "#4d3d75"
        readonly property color primaryContainerText: "#e9ddff"
        readonly property color secondary: "#cbc2db"
        readonly property color secondaryText: "#332d41"
        readonly property color secondaryContainer: "#4a4458"
        readonly property color secondaryContainerText: "#e8def8"
        readonly property color tertiary: "#efb8c8"
        readonly property color tertiaryText: "#4a2532"
        readonly property color tertiaryContainer: "#633b48"
        readonly property color tertiaryContainerText: "#ffd9e3"
        readonly property color error: "#ffb4ab"
        readonly property color errorText: "#690005"
        readonly property color errorContainer: "#93000a"
        readonly property color errorContainerText: "#ffdad6"
        readonly property color surface: "#141218"
        readonly property color surfaceText: "#e6e0e9"
        readonly property color surfaceVariantText: "#cac4cf"
        readonly property color surfaceContainerLowest: "#0f0d13"
        readonly property color surfaceContainerLow: "#1d1b20"
        readonly property color surfaceContainer: "#211f24"
        readonly property color surfaceContainerHigh: "#2b292f"
        readonly property color surfaceContainerHighest: "#36343a"
        readonly property color outline: "#948f99"
        readonly property color outlineVariant: "#49454e"
        readonly property color inverseSurface: "#e6e0e9"
        readonly property color inverseOnSurface: "#322f35"
        readonly property color inversePrimary: "#65558f"
    }

    readonly property QtObject scheme: darkMode ? dark : light
}
